services:
    opifer.revisions.annotation_reader:
        class: Opifer\Revisions\Mapping\AnnotationReader

    opifer.revisions.revision_manager:
        class: Opifer\Revisions\RevisionManager
        arguments: ['@doctrine.orm.default_entity_manager', '@opifer.revisions.annotation_reader']